name: flutter_mobile_ui
description: A mobile UI in flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dbus: ^0.6.3
  desktop_entry:
    path: ../desktop_entry
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  gsettings: ^0.2.0
  process: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  stack11_linting:
    git:
      url: https://gitlab.com/stack11-oss/linting

flutter:
  uses-material-design: true
